export const CREATE_PROFIT = 'CREATE_PROFIT';
export const FETCH_PROFITS = 'FETCH_PROFITS';
export const FETCH_PROFIT = 'FETCH_PROFIT';
export const DELETE_PROFIT = 'DELETE_PROFIT';
export const EDIT_PROFIT = 'EDIT_PROFIT';
