version: '3'
services:
  mysql:
    restart: always
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: pfa
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  common-service:
    build:
      dockerfile: Dockerfile
      context: ./common-service
    depends_on:
      - mysql
    ports:
      - 10080:10080      
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      WAIT_HOSTS: mysql:3306
  account-service:
    build:
      dockerfile: Dockerfile
      context: ./account-service
    depends_on:
      - mysql
    ports:
      - 10081:10081
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      STOCK_SERVICE_ENDPOINT: http://stock-service:10082
      WAIT_HOSTS: mysql:3306
  stock-service:
    build:
      dockerfile: Dockerfile
      context: ./stock-service
    depends_on:
      - mysql
    ports:
      - 10082:10082
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      WAIT_HOSTS: mysql:3306
