version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: pfa-nginx
    ports:
      - 10080:80
    depends_on:
      - common-service
      - account-service
      - stock-service
      - job-service
  common-service:
    build:
      dockerfile: Dockerfile
      context: ./common-service
    image: pfa-common-service
    ports:
      - 18080:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.136:3306/pfa
      SPRING_DATASOURCE_USERNAME: hai
      SPRING_DATASOURCE_PASSWORD: hai
    command: ["java", "-jar", "-Dspring.profiles.active=dockercompose", "common-service.jar"]
  account-service:
    build:
      dockerfile: Dockerfile
      context: ./account-service
    image: pfa-account-service
    ports:
      - 18081:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.136:3306/pfa
      SPRING_DATASOURCE_USERNAME: hai
      SPRING_DATASOURCE_PASSWORD: hai
      STOCK_SERVICE_ENDPOINT: http://stock-service:8080
    command: ["java", "-jar", "-Dspring.profiles.active=dockercompose", "account-service.jar"]
  stock-service:
    build:
      dockerfile: Dockerfile
      context: ./stock-service
    image: pfa-stock-service
    ports:
      - 18082:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.136:3306/pfa
      SPRING_DATASOURCE_USERNAME: hai
      SPRING_DATASOURCE_PASSWORD: hai
      REDIS_URL: redis://192.168.1.136:6379
    command: ["java", "-jar", "-Dspring.profiles.active=dockercompose", "stock-service.jar"]
  job-service:
    build:
      dockerfile: Dockerfile
      context: ./job-service
    image: pfa-job-service
    ports:
      - 18083:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.136:3306/pfa
      SPRING_DATASOURCE_USERNAME: hai
      SPRING_DATASOURCE_PASSWORD: hai
      STOCK_SERVICE_ENDPOINT: http://stock-service:8080
    command: ["java", "-jar", "-Dspring.profiles.active=dockercompose", "job-service.jar"]
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: pfa-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "13000:3000"
    stdin_open: true
