version: '3'
services:
  # Replace with Redis running in WSL
  # redis:
    # restart: always
    # build:
      # dockerfile: Dockerfile
      # context: ./redis
    # image: pfa-redis
    # ports:
      # - 6379:6379
  # Replace with local MySQL
  # mysql:
    # restart: always
    # build:
      # dockerfile: Dockerfile
      # context: ./mysql
    # image: pfa-mysql
    # environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: pfa
      # MYSQL_USER: pfa
      # MYSQL_PASSWORD: pfa
    # volumes:
      # - ./data/mysql:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password
    # ports:
      # - 3306:3306
    # security_opt:
      # - seccomp:unconfined      
    # healthcheck:
      # test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      # interval: 2s
      # timeout: 20s
      # retries: 10
  # elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    # ports:
      # - 9200:9200
      # - 9300:9300
    # environment:
      # - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # volumes:
      # - C:/projects/pfa/data/elasticsearch:/usr/share/elasticsearch/data
  # kibana:
    # image: docker.elastic.co/kibana/kibana:7.9.2
    # ports:
      # - 5601:5601
  # logstash:
    # image: docker.elastic.co/logstash/logstash:7.9.2
    # ports:
      # - 5044:5044
# volumes:
  # mysqldatadir:
