version: '3'
services:
  redis:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./redis
    ports:
      - 16379:6379
  mysql:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mysql
    environment:
      MYSQL_DATABASE: pfa
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  common-service:
    build:
      dockerfile: Dockerfile
      context: ./common-service
    depends_on:
      - mysql
    ports:
      - 10080:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: ["/wait-for-it.sh", "mysql:3306", "--timeout=300", "--", "java", "-jar", "-Dspring.profiles.active=dockercompose", "common-service.jar"]
  account-service:
    build:
      dockerfile: Dockerfile
      context: ./account-service
    depends_on:
      - mysql
    ports:
      - 10081:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      STOCK_SERVICE_ENDPOINT: http://stock-service:8080
    command: ["/wait-for-it.sh", "mysql:3306", "--timeout=300", "--", "java", "-jar", "-Dspring.profiles.active=dockercompose", "account-service.jar"]
  stock-service:
    build:
      dockerfile: Dockerfile
      context: ./stock-service
    depends_on:
      - mysql
      - redis
    ports:
      - 10082:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_URL: redis://redis:6379
    command: ["/wait-for-it.sh", "mysql:3306", "--timeout=300", "--", "java", "-jar", "-Dspring.profiles.active=dockercompose", "stock-service.jar"]
  job-service:
    build:
      dockerfile: Dockerfile
      context: ./job-service
    depends_on:
      - mysql
    ports:
      - 10083:8080
    environment:
      ENV: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      STOCK_SERVICE_ENDPOINT: http://stock-service:8080
    command: ["/wait-for-it.sh", "mysql:3306", "--timeout=300", "--", "java", "-jar", "-Dspring.profiles.active=dockercompose", "job-service.jar"]
