version: '2.4'
services:
  nginx:
    mem_limit: '50M'
    memswap_limit: '50M'
    restart: always
    build:
      dockerfile: Dockerfile-prod
      context: ./nginx
    image: pfa-nginx
    ports:
      - 10080:80
    depends_on:
      - common-service
      - account-service
      - stock-service
      - job-service
      - frontend
  common-service:
    mem_limit: '200M'
#    memswap_limit: '200M'
    build:
      dockerfile: Dockerfile
      context: ./common-service
    image: pfa-common-service
    environment:
      SPRING_APPLICATION_JSON: '{"server.port":8080}'
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_HOST: host.docker.internal
      COMMON_SERVICE_ENDPOINT: http://common-service:8080
  account-service:
    mem_limit: '200M'
#    memswap_limit: '200M'
    build:
      dockerfile: Dockerfile
      context: ./account-service
    image: pfa-account-service
    environment:
      SPRING_APPLICATION_JSON: '{"server.port":8080}'
      SERVER_PORT: 8080
      SERVER_TOMCAT_MAXTHREADS: 1
      JAVA_OPTS: -Xmx100m -Xms100m
      SPRING_PROFILES_ACTIVE: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_HOST: host.docker.internal
      STOCK_SERVICE_ENDPOINT: http://stock-service:8080
      COMMON_SERVICE_ENDPOINT: http://common-service:8080
  stock-service:
    mem_limit: '200M'
#    memswap_limit: '200M'
    build:
      dockerfile: Dockerfile
      context: ./stock-service
    image: pfa-stock-service
    environment:
      SPRING_APPLICATION_JSON: '{"server.port":8080}'
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_HOST: host.docker.internal
      COMMON_SERVICE_ENDPOINT: http://common-service:8080
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
    ports:
      - 8000:8000
  job-service:
    mem_limit: '200M'
#    memswap_limit: '200M'
    build:
      dockerfile: Dockerfile
      context: ./job-service
    image: pfa-job-service
    environment:
      SPRING_APPLICATION_JSON: '{"server.port":8080}'
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dockercompose
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/pfa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_HOST: host.docker.internal
      STOCK_SERVICE_ENDPOINT: http://stock-service:8080
      COMMON_SERVICE_ENDPOINT: http://common-service:8080
  frontend:
    mem_limit: '50M'
    memswap_limit: '50M'
    build:
      dockerfile: Dockerfile-prod
      context: ./frontend
    image: pfa-frontend
