export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const FETCH_PORTFOLIOS = 'FETCH_PORTFOLIOS';
export const FETCH_PORTFOLIO = 'FETCH_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';
export const EDIT_PORTFOLIO = 'EDIT_PORTFOLIO';
