apiVersion: v1
kind: Pod
metadata:
  name: account-service-pod
  labels:
    component: account-service
spec:
  containers:
    - name: account-service
      image: pfa-account-service
      imagePullPolicy: Never
      ports:
        - containerPort: 8080