apiVersion: v1
kind: Service
metadata:
  name: account-service-node-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    component: account-service
        