apiVersion: v1
kind: Pod
metadata:
  name: common-service-pod
  labels:
    component: common-service
spec:
  containers:
    - name: common-service
      image: pfa-common-service
      imagePullPolicy: Never
      ports:
        - containerPort: 8080