apiVersion: v1
kind: Service
metadata:
  name: common-service-node-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    component: common-service
        