apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    component: frontend
spec:
  containers:
    - name: frontend
      image: pfa-frontend
      imagePullPolicy: Never
      ports:
        - containerPort: 3000