apiVersion: v1
kind: Pod
metadata:
  name: job-service-pod
  labels:
    component: job-service
spec:
  containers:
    - name: job-service
      image: pfa-job-service
      imagePullPolicy: Never
      ports:
        - containerPort: 8080