apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    component: redis
spec:
  containers:
    - name: redis
      image: pfa-redis
      imagePullPolicy: Never
      ports:
        - containerPort: 6379