apiVersion: v1
kind: Pod
metadata:
  name: stock-service-pod
  labels:
    component: stock-service
spec:
  containers:
    - name: stock-service
      image: pfa-stock-service
      imagePullPolicy: Never
      ports:
        - containerPort: 8080