apiVersion: v1
kind: Service
metadata:
  name: stock-service-node-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  selector:
    component: stock-service
        