export const CREATE_DIVIDEND = 'CREATE_DIVIDEND';
export const FETCH_DIVIDENDS = 'FETCH_DIVIDENDS';
export const FETCH_DIVIDEND = 'FETCH_DIVIDEND';
export const DELETE_DIVIDEND = 'DELETE_DIVIDEND';
export const EDIT_DIVIDEND = 'EDIT_DIVIDEND';
