apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-service
subsets:
  - addresses:
      - ip: 192.168.86.43
    ports:
      - port: 3306

---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-service
subsets:
  - addresses:
      - ip: 192.168.86.43
    ports:
      - port: 6379
