export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_EXCHANGES = 'FETCH_EXCHANGES';
export const FETCH_ACTIONS = 'FETCH_ACTIONS';
