apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service-deployment
  labels:
    component: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stock-service
  template:
    metadata:
      labels:
        component: stock-service
    spec:
      containers:
        - name: stock-service
          image: pfa-stock-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-cluster-ip-service/pfa
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: dockercompose
            - name: REDIS_URL
              value: redis://redis-cluster-ip-service:6379
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: stock-service
  ports:
    - port: 8080
      targetPort: 8080
